### ISSUE TITLE
Sync not starting anymore at all in Manjaro Linux

### ISSUE THREAD

**Issue by BDGreyson** [FilenCloudDienste/filen-desktop#195]
I'm using Manjaro Linux with KDE Plasma and try to use Filen with the officially provided Appimage.
The app starts, lets me sign in and change settings no problem.

On my previous installation with the same OS, the sync started, but stopped working and was hanging at some random files.
Now I'm giving it a new try on a freshly deleted SSD and a new installation, but it's even worse:

I set up two folders to sync in my settings and I unpaused it:

![grafik](https://github.com/FilenCloudDienste/filen-desktop/assets/50461895/e242de39-1e3e-4b0c-b120-e3df6a5bb451)

But no sync is starting at all. Pausing-unpausing didn't help, force sync doesn't help, and restarting the OS doesn't help either. Filen is constantly telling me everything is synced, but that, sadly, is not true.

I tried creating a new file to force it to re-check, but without anything changing. I also get no errors.

So, thus I tried to use the "upload file" function on a small text file:

![grafik](https://github.com/FilenCloudDienste/filen-desktop/assets/50461895/53d67899-368e-4319-9a16-faf9b02d96cd)

This is just where it sticks. The file just contains the word "Test", but yeah, the upload never finishes but I also don't get any timeouts or errors.

The main-log logfile doesn't show anything useful either, at least not to me:

![grafik](https://github.com/FilenCloudDienste/filen-desktop/assets/50461895/cd7d634f-0dad-4754-9623-d11c66e32f0d)

So, yeah...deleting the Appimage along with the folder in .config and trying it again didn't help either. So, now I have no more idea.

Feel free to tell me if I can provide any more logs, but I just can't get it to work, it seems.

----

Filen Version v2.0.16 (64bit AppImage)
System Info:
Manjaro Linux
KDE-Plasma-Version: 5.27.4
KDE-Frameworks: 5.105.0
Qt-Version: 5.15.9
Kernel-Version: 6.1.26-1-Manjaro (64bit)
Graphics platform: X11

**Comment by dburba** [comment]
I have exactly the same issue on Linux Mint 21.1 Cinnamon. New/edited files in local folder are not uploaded to cloud. I must delete and re-add sync location. AppImage v2.0.22

**Comment by BDGreyson** [comment]
Okay, in my case, neither the current nor previous version worked after "reinstalls". Then, three days or so ago, I used the 2.0.16 AppImage again, once again, not working. Then, suddenly, yesterday, it started working again despite no update to the app or any other Manjaro parts. Soo...right now everything seems to work again but I have no clue why or why it stopped in the first place.

Still, thanks for the ideas, I hope it'll keep running now, I wish I would've found the culprit, but maybe it's gone for good now. 

I'll leave this issue open in case anyone can help dburba with the newest problem, but at least from my side things work again, for now. 😅

**Comment by adorbabble** [comment]
It seems that I now have the same issue on Windows 10, Filen 2.0.24… New files or modified have troubleA file that I updated this morning won’t be uploaded to the cloud. I went into the settings, noticed that strangely, selective sync checkboxes had all been inverted ! After setting them correctly again, a file that had not been uploaded previously was 

I tried deleting the sync location and creating it again,

**Comment by dburba** [comment]
AppImage was updated to v2.0.24 and sync is working again in both ways. It looks like the issues have been fixed.

**Comment by adorbabble** [comment]
Not fixed for me, so I’m currently reuploading the entire folder into a fresh folder on the cloud with a new sync. I’m actually not sure when this problem started for me because I didn’t notice it at first, but most likely when I upgraded to 2.0.21 or 2.0.22

**Comment by Dwynr** [comment]
Closing, can't reproduce on a fresh Linux install (GNOME, debian based).
